### ISSUE TITLE
remove max length?

### ISSUE THREAD

**Issue by a8underscore** [vladaad/discordcompressor#17]
this seems unneeded, maybe make a notice that above X length the quality gets trashy

**Comment by vladaad** [comment]
The max length can be indirectly adjusted in settings using BitrateLimitMin. Encoder settings included by default in DiscordCompressor aren't at all suitable below the limit, however the new rewrite branch fixes that by using automatic resolution selection and completely removes the minimum limit.

**Comment by vladaad** [comment]
Max length limit is now removed, thanks to much improved encoder choice. Enjoy your 3mb shrek :P
